name: CI 
on: [push, pull_request]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
        
    - name: Build
      run: dotnet build **/Everything.sln
      
    - name: Test
      run: dotnet test --no-build --verbosity normal
      
    - name: Publish
      if: startsWith(github.ref, 'refs/heads/master')
      run: nuget push **\*.nupkg -Source 'https://api.nuget.org/v3/index.json' -ApiKey ${{secrets.NUGET_API_KEY}}
